### ISSUE TITLE
nightly.link returns cached artifact

### ISSUE THREAD

**Issue by XYQuadrat** [oprypin/nightly.link#16]
Hi, let me preface this by saying just how awesome this service is - a small, simple idea implemented very well that is super useful to develop custom solutions with.

I'm trying to download the latest artifact from [this workflow](https://github.com/XYQuadrat/polyring/blob/master/.github/workflows/node.js.yml) via `curl -L "https://nightly.link/XYQuadrat/polyring/workflows/node.js/master/static-dist.zip"`. This command is run shortly after a build is finished (the build triggers a webhook on my server, which calls a script with the above mentioned `curl` command inside).

Problematically, I do not receive the latest artifact, but the second newest one when `curl`ing. If I manually open the link in a browser though, everything works fine and if I re-run the script after that, it also picks up the correct artifact. This leads me to believe this is a caching problem. Do you have any idea on how to fix this?

**Comment by oprypin** [comment]
(Sorry, my post somehow sounds angry but that's not intended)

1. Please don't use this service in fully automatic workflows. It makes sense as human-facing, because people aren't gonna write run a script to download something, but it's easy to add such a script into automation.
    * https://github.com/actions/github-script allows you to query and download whatever you want, on your own terms, and with your own quota.
        * In fact, I probably should add instructions for this, but I haven't tried to write the exact code for this yet.
    * Although now I notice that you're not running the download *from* GitHub actions, so getting NodeJS or whatever is somewhat less convenient...

2. The cache of 5 minutes is there and that will not change https://github.com/oprypin/nightly.link/blob/00dcabd3cd5619f5fb4d23cd07ffa807b6699387/src/nightly_link.cr#L401
    * This means that, no matter what you do, if you're just unlucky and someone else used that link in the last 5 minutes you'll be hit by the cache.

3. I suspect that **maybe the source of your current complaint isn't due to caching**, just that GitHub's search hasn't received the info about the latest run yet. Maybe adding more delay would help, but (2) will always apply still.

4. > the build triggers a webhook on my server
    
    Doesn't the hook contain the ID of the finished run? If so, just **download using the URL for that exact run**?

**Comment by XYQuadrat** [comment]
Ah, then everything makes sense now. The webhook fires once when the build starts and once when it has completed. Since the script thus also queries the link when the build starts, the result gets cached then and the second query returns the cached version in this case (since build times are very short).

Thanks for clarifying that the service isn't meant for fully automatic workflows. My particular use case makes it rather difficult to use NodeJS to run the scripts and all that, but I'll find a way to adapt to this then.

The hook sadly does not contain the ID of the finished run by default as far as I can tell. 
Thank you for your quick response.
