### ISSUE TITLE
branch names with "/" are revoked on the nightly.link page

### ISSUE THREAD

**Issue by dyfer** [oprypin/nightly.link#27]
Hello,
Thank you for this wonderful tool!
I have found, that branch names that contain `/` character don't pass format check when entered in the entry box on the nightly.link website.

A workaround is to replace `/` with e.g. `-`, and then, after clicking "Get Link", replace back the appropriate character directly in the address bar of the browser. 
EDIT: the workaround doesn't seem to actually work, I can't get artifacts from a branch that has a space in it. Example: https://nightly.link/dyfer/supercollider/workflows/actions/topic/macos-legacy-fixes-rebased

**Comment by oprypin** [comment]
Thanks for the report. The pattern will be recognized in the input correctly now. And the branch with slash was already possible to use but the slash needs to be escaped as such:

https://nightly.link/dyfer/supercollider/workflows/actions/topic%2Fmacos-legacy-fixes-rebased

*Unfortunately* then we still run into issue #26

That link gives you an empty result
because GitHub reports an empty result
https://github.com/dyfer/supercollider/actions?query=event%3Apush+is%3Asuccess+branch%3Atopic%2Fmacos-legacy-fixes-rebased
even though a slightly modified search clearly shows that there have, in fact, been successful builds:
https://github.com/dyfer/supercollider/actions?query=event%3Apush+branch%3Atopic%2Fmacos-legacy-fixes-rebased

**Comment by dyfer** [comment]
Thank you for looking into this! 
I understand that GitHub still reports wrong information. Do you know in what circumstances this happens? Is it due to dashes in the branch name?
