### ISSUE TITLE
Ability to get artifacts for pull requests instead of pushes

### ISSUE THREAD

**Issue by Bluscream** [oprypin/nightly.link#31]
I need a artifact for these: https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=branch%3A1.18+is%3Asuccess

**Comment by oprypin** [comment]
https://nightly.link/ currently will let you download a particular artifact (including from PR) but indeed doesn't have any functionality of finding artifacts of a pull request.

I will consider this feature but it would help to have rationale for needing it.

Meanwhile, make sure you've seen https://nightly.link/ section "Bot that comments on pull requests".

**Comment by Bluscream** [comment]
> I will consider this feature but it would help to have rationale for needing it.

well, just look at the example i posted, it's a branch that doesn't get pushed on but gets a bunch of new releases through pull requests, but the original owner isn't pushing them. people use the artifacts anyway, so it would be great if we could just link that instead of needing to explain to people how to download the latest by hand

**Comment by oprypin** [comment]
> I need a artifact for these: https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=branch%3A1.18+is%3Asuccess

You can instead get them as push events to your fork, not an issue at all:
https://nightly.link/?url=https://github.com/wagyourtail/baritone/blob/1.18/.github/workflows/gradle_build.yml

> it's a branch that doesn't get pushed on but gets a bunch of new releases through pull requests, but the original owner isn't pushing them

Honestly, this to me is a big argument *against* allowing this feature. Particularly because it's being done against the owner's wishes.
It sounds like a way of potentially disguising malware.
Consider this:
* "github.com" and "nightly.link" look like something official.
* The URL includes the repository "cabaletta/baritone" so it looks endorsed by them.
&rarr; You could make a pull request with any content and present it as something "official".

**Comment by Bluscream** [comment]
I will make my own service for this then.
