### ISSUE TITLE
Slow Downloads & Timeout Errors

### ISSUE THREAD

**Issue by HassanAbouelela** [oprypin/nightly.link#42]
The API downloads ~64kB, then hangs there for a few seconds before resuming. I can reproduce this in my programs, and through the site itself. This is not a big deal, but it has caused time-out errors in CI.

I don't have an exact date on when this happened, but my last passing build was on the 23rd 11PM UTC. Everything since has failed. Is this just a temporary hiccup, or something I should fix on my end? Thanks

**Comment by oprypin** [comment]
The website nightly.link only serves HTML pages and **redirects**, never any downloads, so certainly no response would ever reach even 64 kB. So I believe this issue is invalid or is about GitHub itself.

Separately from that, nightly.link should only be a human-facing website. For programmatic access it will always be a better solution to use GitHub's API directly. That won't needlessly use resources and will save you from nightly.link's **non-existent uptime goal**
