### ISSUE TITLE
No successful runs found for workflow

### ISSUE THREAD

**Issue by GuillaumeDesforges** [oprypin/nightly.link#6]
I get `No successful runs found for workflow` after installing, and giving the link https://github.com/polar-analytics/tap-sklik/blob/actions-setup-tarball/.github/workflows/python-app.yml, while the workflow did run successfully

**Comment by oprypin** [comment]
Yep, that is correct
https://github.com/polar-analytics/tap-sklik/actions?query=event%3Apush+branch%3Aactions-setup-tarball

**Comment by GuillaumeDesforges** [comment]
Thanks for your reply.

As I am a noob in GitHub actions, I'd be happy if you could still help me a bit.
The following query does give results: https://github.com/polar-analytics/tap-sklik/actions?query=branch%3Aactions-setup-tarball+workflow%3A%22Python+application%22

Would it be possible to broaden to `pull_request` events as well ?

**Comment by oprypin** [comment]
It is technically possible but makes no sense or is dangerous. That's because anyone (even without any access) can make a pull request against any repo, and we wouldn't want to have a link that represents whatever random action any random person happened to do last. That's why it's limited to actual pushes to the repository. Merging a pull request constitutes a push, maybe you just want to do that.

**Comment by GuillaumeDesforges** [comment]
Makes a lot of sense, thanks!
